resources:
    - name: repo
      type: git
      source:
          uri: https://FZynwala:((github_access_token))@github.com/FZynwala/monorepo-test.git

jobs:
    - name: deploy-backend-job
      plan:
          - get: repo
            trigger: true # tell Concourse to trigger this job when new versions are emitted
          - task: deploy-backend-task
            config:
                platform: linux
                image_resource:
                    type: registry-image
                    source:
                        repository: node
                        tag: 14.17.0
                inputs: # add the get step as an input to this task
                    - name: repo
                run: # read the file from the get step
                    path: sh
                    args:
                        - -exc
                        - |
                            curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
                            cat > ~/.netrc <<EOF
                            machine git.heroku.com
                              login ((HEROKU_EMAIL))
                              password ((HEROKU_TOKEN))
                            machine git.heroku.com
                              login ((HEROKU_EMAIL))
                              password ((HEROKU_TOKEN))
                            EOF
                            cat ~/.netrc
                            heroku login
                            cd repo
                            ls
                            yarn
                            cd packages/nest-server
                            heroku git:remote -a nest-server-test-app
                            git push heroku master
