resources:
    - name: repo
      type: git
      source:
          uri: https://FZynwala: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@github.com/FZynwala/monorepo-test.git

jobs:
    - name: deploy-frontend-job
      plan:
          - get: repo
            trigger: true # tell Concourse to trigger this job when new versions are emitted
          - task: deploy-frontend-task
            config:
                platform: linux
                image_resource:
                    type: registry-image
                    source:
                        repository: node
                        tag: 12.16.1
                inputs: # add the get step as an input to this task
                    - name: repo
                run: # read the file from the get step
                    path: sh
                    args:
                        - -cx
                        - |
                            git config --global user.email "filipzynwala@gmail.com"
                            git config --global user.name "FZynwala"
                            cd repo
                            yarn
                            cd packages/frontend
                            yarn build
                            yarn deploy
